### ISSUE TITLE
System font stack not loading properly on MacOS

### ISSUE THREAD

**Issue by erler** [paritytech/contracts-ui#105]
Currently the `system` font in `base.css` seems to default to Tahoma on MacOS (both Chrome and Firefox) and it doesn't render nicely.

<img width="1301" alt="Screenshot 2021-09-14 at 12 12 23" src="https://user-images.githubusercontent.com/7072141/133240058-15907a93-ea1e-4187-846d-2465803cc96c.png">

Using system fonts the GH way works however:
```css
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";
}
```
<img width="1303" alt="Screenshot 2021-09-14 at 12 11 46" src="https://user-images.githubusercontent.com/7072141/133240272-c932e0d6-7828-42a2-9b34-93918b9a1a25.png">

Though I am aware that declaring them through font-face is more performant.
https://css-tricks.com/snippets/css/system-font-stack/#method-2-system-font-stacks
